spring:
  cloud:
    azure:
      storage:
        blob:
          enabled: true
          credential:
            managed-identity-enabled: true
          account-name: ${BLOB_ACCOUNT_NAME}
          container-name: ${BLOB_CONTAINER_NAME}
